version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    env_file:
      - apps/backend/.env
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - apps/backend/.env
    environment:
      REDIS_PASSWORD: ${REDIS_DB_PASS}
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
