name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: '1.0.30'
        cache: true
        
    - name: Install dependencies
      run: bun install

    - name: Build
      run: bun run build

    - name: Lint
      run: bun run lint
